version: '3'
services: 
  # ------------------------------------------------
  # DataStax Enterprise
  # ------------------------------------------------
  dse:
    image: datastax/dse-server:6.8.9
    command: [ -s -g -k ]
    ports:
      - 9042:9042
      - 8983:8983
      - 8182:8182
    #depends_on:
    #   - opscenter  
    environment:
      - DS_LICENSE=accept
      - DC=dc1
      - JVM_EXTRA_OPTS=-Xmx2g -Xms2g
      - NUM_TOKENS=32
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    volumes:
      - "dse-storage:/var/lib/cassandra"

  # ------------------------------------------------
  # One instance of DataStax Studio
  # ------------------------------------------------
  studio:
     image: datastax/dse-studio:6.8.9
     ports:
       - 9091:9091
     depends_on:
       - dse
     environment:
       DS_LICENSE: accept
     volumes:
       - "dse-studio-storage:/var/lib/datastax-studio"
  
  # ------------------------------------------------
  # OpsCenter
  # ------------------------------------------------
  opscenter:
    image: datastax/dse-opscenter:6.8.9
    ports:
      - 8888:8888
    environment:
      - DS_LICENSE=accept

  # ------------------------------------------------
  # Confluent Platform
  # ------------------------------------------------
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: cp-zookeeper
    container_name: cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  cp-kafka:
    image: confluentinc/cp-server:6.0.1
    hostname: cp-kafka
    container_name: cp-kafka
    depends_on:
      - cp-zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'cp-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: cp-kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - cp-kafka-storage:/var/lib/kafka/data

  cp-schema-registry:
    image: confluentinc/cp-schema-registry:6.0.1
    hostname: cp-schema-registry
    container_name: cp-schema-registry
    depends_on:
      - cp-kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: cp-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'cp-kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  cp-control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: cp-control-center
    container_name: cp-control-center
    depends_on:
      - cp-kafka
      - cp-schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'cp-kafka:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://cp-schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

volumes:
  dse-storage: {}
  dse-studio-storage: {}
  cp-kafka-storage: {}
